[package]
name = "hdown"
version = "0.1.0"
authors = ["owen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "0.11.4"
scraper = "0.11.0"
regex = "1.3.7"
clap = "2.33.0"
lazy_static = "1.4.0"